
notifications:
  email: false

env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

addons:
  apt:
    packages:
    - bash
    - curl

install: true
before_install:
- sudo apt-get update -yqq >/dev/null
- sudo apt-get install -yqq --no-install-suggests --no-install-recommends
  tree jq python-pip curl bash sudo >/dev/null
#
- sudo pip install httpie >/dev/null 2>&1
#
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 3000 80 >/dev/null

script:
- export root=$(pwd)
#
- ./gradlew >/dev/null
- java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -Djava.net.preferIPv4Stack=true ./build/*-microbundle.jar &
- wait_for 8080
- sleep 15
- http :8080/v1 string=one
- http :8080/v1 string=two
- http :8080/v1 string=three
- http :8080/v1
- http :8080
- stop_any 80 8080
#
- ./mvnw >/dev/null
- ./mvnw -Pbundle
- java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -Djava.net.preferIPv4Stack=true ./target/*-microbundle.jar &
- wait_for 8080
- sleep 15
- http :8080/v1 string=one
- http :8080/v1 string=two
- http :8080/v1 string=three
- http :8080/v1
- http :8080
- stop_any 80 8080

before_deploy:
- cd ${root}
- ./mvnw -Pdocs
- mkdir -p ./target/generated-docs
- cp -Rf ./target/generated-docs/index.html ./target/generated-docs/404.html

deploy:
  provider: pages
  skip-cleanup: true
  # travis encrypt GITHUB_TOKEN=<your github repo token> --add
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: target/generated-docs
  target_branch: gh-pages

before_cache:
- for item in $(find ~/.gradle -name "*.lock");
    do sudo rm -rf $item ;
  done

